# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-09 04:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='users_tb',
        ),
    ]
