# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-09 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_users_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(default=20, verbose_name=3),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='123456', max_length=32),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='user', max_length=32),
        ),
    ]
